name: Deploy Next.js App and CDK Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v3
      
      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # 3. Install Project Dependencies
      - name: Install Dependencies
        working-directory: cipher-infra
        run: |
          npm ci
          npm install --save aws-cdk-lib
          npm install --save-dev @types/node ts-node
          npm install -g aws-cdk

      # 4. Verify CDK Installation
      - name: Verify CDK Installation
        run: cdk --version
      
      # 5. Deploy S3 Bucket
      - name: Deploy Bucket
        working-directory: cipher-infra
        run: |
          cdk deploy "*Bucket*" --require-approval never --outputs-file bucket-outputs.json
      
      # Upload Deployment Package to S3
      - name: Upload Deployment Package
        run: |
          BUCKET_NAME=$(jq -r '.CipherStack.DeploymentBucketName' cipher-infra/bucket-outputs.json)
          echo "Uploading deployment package to bucket: ${BUCKET_NAME}"
          aws s3 cp deploy.zip "s3://${BUCKET_NAME}/deploy.zip"
      
      #  Verify Data Upload
      - name: Verify Deployment Package
        run: |
          BUCKET_NAME=$(jq -r '.CipherStack.DeploymentBucketName' cipher-infra/bucket-outputs.json)
          aws s3 ls "s3://${BUCKET_NAME}/deploy.zip" || exit 1

      #  Deploy EC2 and Other Infrastructure
      - name: Deploy EC2 Stack
        working-directory: cipher-infra
        run: |
          cdk deploy "*EC2*" --require-approval never --outputs-file ec2-outputs.json
