jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Build Next.js App in Root Folder
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Next.js Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Package Application
        run: |
          zip -r deploy.zip .next package.json package-lock.json public next.config.js app pages

      # Step 3: Setup CDK in Cipher-Infra Folder
      - name: Install CDK Dependencies
        working-directory: cipher-infra
        run: npm ci

      - name: Build CDK
        working-directory: cipher-infra
        run: npm run build

      - name: Deploy Infrastructure
        working-directory: cipher-infra
        run: cdk deploy --require-approval never

      # Step 4: Upload to S3 and Deploy to EC2
      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://${{ env.DEPLOY_BUCKET }}/deploy.zip
