name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Build Next.js
      - name: Install Root Dependencies
        run: npm ci
      
      - name: Build Next.js
        run: npm run build
      
      - name: Package Application
        run: |
          zip -r deploy.zip .next package.json package-lock.json public app pages next.config.js

      # AWS Setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      # CDK Deploy
      - name: CDK Setup
        working-directory: cipher-infra
        run: |
          npm ci
          npm install -g aws-cdk
          
      - name: CDK Bootstrap
        working-directory: cipher-infra
        run: cdk bootstrap
        
      - name: Deploy Infrastructure
        working-directory: cipher-infra
        run: |
          cdk deploy --require-approval never --outputs-file outputs.json
          
      - name: Upload to S3
        run: |
          BUCKET_NAME=$(jq -r '.CipherInfraStack.DeploymentBucketName' cipher-infra/outputs.json)
          aws s3 cp deploy.zip "s3://${BUCKET_NAME}/deploy.zip"