name: Deploy Next.js App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v3
      
      # 1. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      # 2. Build Next.js first
      - name: Install Next.js Dependencies
        run: npm ci
      
      - name: Build Next.js
        run: npm run build
        env:
          SKIP_TYPE_CHECK: true
        
      - name: Package Application
        run: |
          echo "Creating deployment package..."
          zip -r deploy.zip .next package.json package-lock.json public node_modules
          echo "Package created successfully"

      # 3. Deploy CDK stack
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      # 4. Upload to S3 BEFORE deploying EC2
      - name: Setup CDK
        working-directory: cipher-infra
        run: |
          npm ci
          npm install -g aws-cdk
      
      - name: Deploy S3 Bucket First
        working-directory: cipher-infra
        run: |
          # Deploy only the S3 bucket stack first
          cdk deploy "*Bucket*" --require-approval never --outputs-file bucket-outputs.json
          
      - name: Upload to S3
        working-directory: cipher-infra
        run: |
          BUCKET_NAME=$(jq -r '.CipherStack.DeploymentBucketName' bucket-outputs.json)
          echo "Uploading to bucket: ${BUCKET_NAME}"
          aws s3 cp ../deploy.zip "s3://${BUCKET_NAME}/deploy.zip"
          
      # 5. Now deploy the rest of the infrastructure
      - name: Deploy Main Infrastructure
        working-directory: cipher-infra
        run: |
          cdk deploy --require-approval never --outputs-file outputs.json